<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.davivienda.com/xml/ConsultaTotalesTarjetaCreditoCafeteraAgropecuaria" xmlns:ns0="http://www.davivienda.com/xml/ConsultaTotalesTarjetaCreditoCafeteraAgropecuaria" xmlns:wsp200607="http://www.w3.org/2006/07/ws-policy" xmlns:wsp200409="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:schema>
      <xsd:import schemaLocation="ConsultaTotalesTarjetaCreditoCafeteraAgropecuaria.xsd1.xsd" namespace="http://www.davivienda.com/xml/ConsultaTotalesTarjetaCreditoCafeteraAgropecuaria"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ConsultaMaestraFija_in">
    <wsdl:part name="ConsTotTCCafAgrRequest" element="xsns:ConsTotTCCafAgrRequest" xmlns:xsns="http://www.davivienda.com/xml/ConsultaTotalesTarjetaCreditoCafeteraAgropecuaria"/>
  </wsdl:message>
  <wsdl:message name="ConsultaMaestraFija_out">
    <wsdl:part name="ConsTotTCCafAgrResponse" element="xsns:ConsTotTCCafAgrResponse" xmlns:xsns="http://www.davivienda.com/xml/ConsultaTotalesTarjetaCreditoCafeteraAgropecuaria"/>
  </wsdl:message>
  <wsdl:portType name="ConsultaMaestraFijaPortType">
    <wsdl:operation name="ConsultaMaestraFija">
      <wsdl:input name="ConsultaMaestraFija_Input" message="ns0:ConsultaMaestraFija_in"/>
      <wsdl:output name="ConsultaMaestraFija_Output" message="ns0:ConsultaMaestraFija_out"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultaMaestraFijaSOAP_HTTP_Binding" type="ns0:ConsultaMaestraFijaPortType">
    <soap11:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="ConsultaMaestraFija">
      <soap11:operation soapAction="" style="document"/>
      <wsdl:input name="ConsultaMaestraFija_Input">
        <soap11:body parts="ConsTotTCCafAgrRequest" use="literal"/>
      </wsdl:input>
      <wsdl:output name="ConsultaMaestraFija_Output">
        <soap11:body parts="ConsTotTCCafAgrResponse" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ConsultaMaestraFijaSOAP_HTTP_Service">
    <wsdl:port name="ConsultaMaestraFijaSOAP_HTTP_Port" binding="ns0:ConsultaMaestraFijaSOAP_HTTP_Binding">
      <soap11:address location="http://90.4.28.5:80/ESBService/ConsultaTotalesTarjetaCreditoCafeteraAgropecuaria"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>