<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.davivienda.com/xml/ConsultaSaldosProductoNoConsumo" xmlns:ns0="http://www.davivienda.com/xml/ConsultaSaldosProductoNoConsumo" xmlns:wsp200607="http://www.w3.org/2006/07/ws-policy" xmlns:wsp200409="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:schema>
      <xsd:import schemaLocation="ConsultaSaldosProductoNoConsumo.xsd1.xsd" namespace="http://www.davivienda.com/xml/ConsultaSaldosProductoNoConsumo"/>
      <xsd:import schemaLocation="ConsultaSaldosProductoNoConsumo.xsd2.xsd" namespace="http://www.davivienda.com/xml/ConsultaSaldosProductoNoConsumo"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ConsultaSaldosProductoNoConsumo_in">
    <wsdl:part name="ConsultaSaldosProductoNoConsumo" element="xsns:ConsultaSaldosProductoNoConsumo" xmlns:xsns="http://www.davivienda.com/xml/ConsultaSaldosProductoNoConsumo"/>
  </wsdl:message>
  <wsdl:message name="ConsultaSaldosProductoNoConsumo_out">
    <wsdl:part name="ConsultaSaldosProductoNoConsumoResponse" element="xsns:ConsultaSaldosProductoNoConsumoResponse" xmlns:xsns="http://www.davivienda.com/xml/ConsultaSaldosProductoNoConsumo"/>
  </wsdl:message>
  <wsdl:portType name="ConsultaSaldosProductoNoConsumoPortType">
    <wsdl:operation name="ConsultaSaldosProductoNoConsumo">
      <wsdl:input name="ConsultaSaldosProductoNoConsumo_Input" message="ns0:ConsultaSaldosProductoNoConsumo_in"/>
      <wsdl:output name="ConsultaSaldosProductoNoConsumo_Output" message="ns0:ConsultaSaldosProductoNoConsumo_out"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FabricaCredito04_HTTP_Binding" type="ns0:ConsultaSaldosProductoNoConsumoPortType">
    <soap11:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="ConsultaSaldosProductoNoConsumo">
      <soap11:operation soapAction="" style="document"/>
      <wsdl:input name="ConsultaSaldosProductoNoConsumo_Input">
        <soap11:body parts="ConsultaSaldosProductoNoConsumo" use="literal"/>
      </wsdl:input>
      <wsdl:output name="ConsultaSaldosProductoNoConsumo_Output">
        <soap11:body parts="ConsultaSaldosProductoNoConsumoResponse" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FabricaCredito04_HTTP_Service">
    <wsdl:port name="FabricaCredito04_HTTP_Port" binding="ns0:FabricaCredito04_HTTP_Binding">
      <soap11:address location="http://90.4.28.5:80/ESBService/ConsultaSaldosProductoNoConsumo"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>