<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.davivienda.com/xml/ConsultaSaldosCredFechaCorte" xmlns:ns0="http://www.davivienda.com/xml/ConsultaSaldosCredFechaCorte" xmlns:wsp200607="http://www.w3.org/2006/07/ws-policy" xmlns:wsp200409="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:schema>
      <xsd:import schemaLocation="ConsultaSaldosCredFechaCorte.xsd1.xsd" namespace="http://www.davivienda.com/xml/ConsultaSaldosCredFechaCorte"/>
      <xsd:import schemaLocation="ConsultaSaldosCredFechaCorte.xsd2.xsd" namespace="http://www.davivienda.com/xml/ConsultaSaldosCredFechaCorte"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ConsultaSaldosCredFechaCorte_in">
    <wsdl:part name="ConsultaSaldosCredFechaCorte" element="xsns:ConsultaSaldosCredFechaCorte" xmlns:xsns="http://www.davivienda.com/xml/ConsultaSaldosCredFechaCorte"/>
  </wsdl:message>
  <wsdl:message name="ConsultaSaldosCredFechaCorte_out">
    <wsdl:part name="ConsultaSaldosCredFechaCorteResponse" element="xsns:ConsultaSaldosCredFechaCorteResponse" xmlns:xsns="http://www.davivienda.com/xml/ConsultaSaldosCredFechaCorte"/>
  </wsdl:message>
  <wsdl:portType name="ConsultaSaldosCredFechaCortePortType">
    <wsdl:operation name="ConsultaSaldosCredFechaCorte">
      <wsdl:input name="ConsultaSaldosCredFechaCorte_Input" message="ns0:ConsultaSaldosCredFechaCorte_in"/>
      <wsdl:output name="ConsultaSaldosCredFechaCorte_Output" message="ns0:ConsultaSaldosCredFechaCorte_out"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultaSaldosCredFechaCorte_Binding" type="ns0:ConsultaSaldosCredFechaCortePortType">
    <soap11:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="ConsultaSaldosCredFechaCorte">
      <soap11:operation soapAction="" style="document"/>
      <wsdl:input name="ConsultaSaldosCredFechaCorte_Input">
        <soap11:body parts="ConsultaSaldosCredFechaCorte" use="literal"/>
      </wsdl:input>
      <wsdl:output name="ConsultaSaldosCredFechaCorte_Output">
        <soap11:body parts="ConsultaSaldosCredFechaCorteResponse" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ConsultaSaldosCredFechaCorte_Service">
    <wsdl:port name="ConsultaSaldosCredFechaCorte_Port" binding="ns0:ConsultaSaldosCredFechaCorte_Binding">
      <soap11:address location="http://90.4.28.5:80/ESBService/ConsultaSaldosCredFechaCorte"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>