<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.davivienda.com/xml/ConsultaSaldosAhorros" xmlns:ns0="http://www.davivienda.com/xml/ConsultaSaldosAhorros" xmlns:wsp200607="http://www.w3.org/2006/07/ws-policy" xmlns:wsp200409="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:schema>
      <xsd:import schemaLocation="ConsultaSaldosAhorros.xsd1.xsd" namespace="http://www.davivienda.com/xml/ConsultaSaldosAhorros"/>
      <xsd:import schemaLocation="ConsultaSaldosAhorros.xsd2.xsd" namespace="http://www.davivienda.com/xml/ConsultaSaldosAhorros"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ConsultaSaldosAhorros_in">
    <wsdl:part name="ConsultaSaldosAhorros" element="xsns:ConsultaSaldosAhorros" xmlns:xsns="http://www.davivienda.com/xml/ConsultaSaldosAhorros"/>
  </wsdl:message>
  <wsdl:message name="ConsultaSaldosAhorros_out">
    <wsdl:part name="ConsultaSaldosAhorrosResponse" element="xsns:ConsultaSaldosAhorrosResponse" xmlns:xsns="http://www.davivienda.com/xml/ConsultaSaldosAhorros"/>
  </wsdl:message>
  <wsdl:portType name="ConsultaSaldosAhorros_MsgSetPortType">
    <wsdl:operation name="ConsultaSaldosAhorros">
      <wsdl:input name="ConsultaSaldosAhorros_Input" message="ns0:ConsultaSaldosAhorros_in"/>
      <wsdl:output name="ConsultaSaldosAhorros_Output" message="ns0:ConsultaSaldosAhorros_out"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Operaciones07_HTTP_Binding" type="ns0:ConsultaSaldosAhorros_MsgSetPortType">
    <soap11:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="ConsultaSaldosAhorros">
      <soap11:operation soapAction="" style="document"/>
      <wsdl:input name="ConsultaSaldosAhorros_Input">
        <soap11:body parts="ConsultaSaldosAhorros" use="literal"/>
      </wsdl:input>
      <wsdl:output name="ConsultaSaldosAhorros_Output">
        <soap11:body parts="ConsultaSaldosAhorrosResponse" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Operaciones07_HTTP_Service">
    <wsdl:port name="Operaciones07_HTTP_Port" binding="ns0:Operaciones07_HTTP_Binding">
      <soap11:address location="http://90.4.28.5:80/ESBService/ConsultaSaldosAhorros"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>