<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.davivienda.com/xml/ConsultaFondosDeInversion" xmlns:ns0="http://www.davivienda.com/xml/ConsultaFondosDeInversion" xmlns:wsp200607="http://www.w3.org/2006/07/ws-policy" xmlns:wsp200409="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:schema>
      <xsd:import schemaLocation="ConsultaFondosDeInversion.xsd1.xsd" namespace="http://www.davivienda.com/xml/ConsultaFondosDeInversion"/>
      <xsd:import schemaLocation="ConsultaFondosDeInversion.xsd2.xsd" namespace="http://www.davivienda.com/xml/ConsultaFondosDeInversion"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ConsultaFondosDeInversion_in">
    <wsdl:part name="ConsultaFondosDeInversion" element="xsns:ConsultaFondosDeInversion" xmlns:xsns="http://www.davivienda.com/xml/ConsultaFondosDeInversion"/>
  </wsdl:message>
  <wsdl:message name="ConsultaFondosDeInversion_out">
    <wsdl:part name="ConsultaFondosDeInversionResponse" element="xsns:ConsultaFondosDeInversionResponse" xmlns:xsns="http://www.davivienda.com/xml/ConsultaFondosDeInversion"/>
  </wsdl:message>
  <wsdl:portType name="SAF_MsgSetPortType">
    <wsdl:operation name="ConsultaFondosDeInversion">
      <wsdl:input name="ConsultaFondosDeInversion_Input" message="ns0:ConsultaFondosDeInversion_in"/>
      <wsdl:output name="ConsultaFondosDeInversion_Output" message="ns0:ConsultaFondosDeInversion_out"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SAF_MsgSetSOAP_HTTP_Binding" type="ns0:SAF_MsgSetPortType">
    <soap11:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="ConsultaFondosDeInversion">
      <soap11:operation soapAction="" style="document"/>
      <wsdl:input name="ConsultaFondosDeInversion_Input">
        <soap11:body parts="ConsultaFondosDeInversion" use="literal"/>
      </wsdl:input>
      <wsdl:output name="ConsultaFondosDeInversion_Output">
        <soap11:body parts="ConsultaFondosDeInversionResponse" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SAFConsultaFondosDeInversion_HTTP_Service">
    <wsdl:port name="SAFConsultaFondosDeInversion_HTTP_Port" binding="ns0:SAF_MsgSetSOAP_HTTP_Binding">
      <soap11:address location="http://90.4.28.5:80/ESBService/ConsultaFondosDeInversion"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>